# Generated by Django 6.0.7 on 2026-07-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='festivals.festival')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='set',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='festivals.artist'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('stage', 'artist', 'start_time', 'end_time'), name='unique_festival_set'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('festival', 'name'), name='unique_artist_name_per_festival'),
        ),
    ]
