# Generated by Django 6.0.7 on 2026-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_stage_options_artist_alter_set_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, upload_to='sets_images/'),
        ),
    ]
