# Generated by Django 6.0.7 on 2026-07-19 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_set_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
